import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from './components/auth/AuthContext';
import AuthGate from './components/auth/AuthGate';
import Footer from "./components/Footer";
import { LoadingProvider } from './components/loader/LoadingProvider';

// Define the local fonts with the correct path structure
const geistSans = localFont({
  src: [
    {
      path: '../../public/fonts/GeistVF.woff',
      weight: '100 900',
    }
  ],
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: [
    {
      path: '../../public/fonts/GeistMonoVF.woff',
      weight: '100 900',
    }
  ],
  variable: "--font-geist-mono",
});

// Correct metadata with the right favicon path
export const metadata = {
  title: "Coincoach",
  description: "Generated by create next app",
  icons: [
    {
      rel: 'icon',
      url: "/images/logo.png", 
    },
    {
      rel: 'apple-touch-icon',
      url: "/images/logo.png", 
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <LoadingProvider>
            <div className="flex flex-col min-h-screen">
              <Navbar />
              <main className="flex-grow">
                <AuthGate>
                  {children}
                </AuthGate>
              </main>
              <Footer />
            </div>
          </LoadingProvider>
        </AuthProvider>
      </body>
    </html>
  );
}